version: '2'
services:
  fusiondirectory:
    restart: always
    image: jrohde/fusiondirectory:latest
    depends_on:
      - openldap
    environment:
	- LDAP_DOMAIN=example.org
	- LDAP_HOST=openldap
	- LDAP_ROOTPW=adminpwd
	- LDAP_PORT=389
	- FD_PLUGINS=samba,dns,argonaut,autofs,certificates,gpg,ldapdump,ldapmanager,mail,postfix,ssh,sudo,systems,weblink,webservice,freeradius,quota,pureftpd
	- FD_WEBSERVICE_SHELL=true
	- FD_SMARTY3_ACL_RENDER=true
   
